wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719261500.0
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      - 105
      3:
      - 2
      - 23
      4: 3.11.5
      5: 0.16.4
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.0001
